on:
  workflow_dispatch:
  schedule:
  - cron: "0 0/1 * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
          node-version: '18.x'
          
    - name: Get dependencies
      run: npm install
      
    - name: Run node.js script
      run: node index.js

    - name: Update Frontend
      run: npm run deploy
